    <footer>
      <!-- Useful Project Management Links -->
      <h2>Explore more</h2>
      <nav>
        <a href="https://nusweek03webtechnologyproject.atlassian.net/jira/software/projects/DEV/boards/1/backlog?atlOrigin=eyJpIjoiZTU1Mjk3NWI3ZTU5NGEyNDgwNDE2NmI2NzgxNmI1MWMiLCJwIjoiaiJ9" target="_blank">
          <img src="images/jira.png" alt="Jira icon" title="Go to G02 Tiramisu Jira workspace">
          Jira Project Space
        </a>
        <a href="https://github.com/MohaNusaiba/COS10026-Wed_1430_G02_Tiramisu_Part2.git" target="_blank">
          <img src="images/github.png" alt="Github icon" title="Go to G02 Github repo">
          Github Repository
        </a>
        <a href="mailto:questions@EcoCityco.org" target="_blank">
          <img src="images/email.png" alt="Email icon" title="Email EcoCity Co">
          Email us
        </a>
        <a href="login.php">
          <img src="images/staff_login.png" alt="Staff Login icon" title="Login to see EOIs and more.">
          Staff Login
        </a>
      </nav>
    </footer>
  </body>
</html>
